# Site Settings
title: Alexes Presswood
email: ampress727@gmail.com
description: >
  This website will be used as my online resume and portfolio, linking any
  visitors to my Github, LinkedIn, Blog, etc.
baseurl: ""
url: "http://alexesmarie27.github.io/portfolio"
twitter_username: alexespresswood
github_username:  alexesmarie27
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM